[build]
  publish = "frontend"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- backend/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"
